import jsPDF from "jspdf";

function ExportPDFButton({ stats, topStudents }) {

  const exportPDF = () => {

    const doc = new jsPDF();

    doc.setFontSize(20);
doc.text("PlacementDNA AI Report", 20, 20);

doc.setFontSize(12);

doc.text("Professional Placement Analytics Dashboard", 20, 35);

doc.text("------------------------------------------", 20, 42);

doc.text("Generated By : PlacementDNA AI", 20, 55);

doc.text(
  "Generated On : " + new Date().toLocaleString(),
  20,
  65
);

doc.text("------------------------------------------", 20, 75);

doc.text("Dashboard Summary", 20, 90);

doc.text(
  `Total Students : ${stats.total_students}`,
  20,
  105
);

doc.text(
  `Average Score : ${stats.avg_score}%`,
  20,
  120
);

doc.text(
  `Hiring Probability : ${stats.avg_hiring}%`,
  20,
  135
);

doc.text(
  `Placement Ready : ${stats.placement_ready}`,
  20,
  150
);

doc.text("------------------------------------------", 20, 170);

doc.text("Top Students", 20, 185);

let y = 200;

topStudents.forEach((student) => {

  doc.text(
    `${student.rank}. ${student.name} - ${student.placement_score}%`,
    20,
    y
  );

  y += 10;

});

doc.save("PlacementDNA_Report.pdf");

  };

  return (

  <button
    onClick={exportPDF}
    className="
      bg-red-600
      hover:bg-red-700
      text-white
      font-semibold
      px-6
      py-3
      rounded-xl
      shadow-lg
      transition-all
      duration-300
    "
  >
    📄 Export PDF
  </button>

);

}

export default ExportPDFButton;